# Generated by Django 4.1.3 on 2022-11-19 18:22

from django.db import migrations, models
import utils.upload


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.upload.get_post_image_path),
        ),
    ]
