version: "3.3"

services:

  db:
    container_name: postgres
    restart: always
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./ibeeam/.env

  web:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./static:/static
      - ./media:/media
    ports:
      - "8000:8000"
    env_file:
      - ./ibeeam/.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web

