# Generated by Django 4.1.3 on 2022-11-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='~~mbvu2F_-zspv)+', max_length=128),
        ),
    ]
