# Generated by Django 4.1.3 on 2022-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='v|q^5B]$_U\x0chY]G7', max_length=128),
        ),
    ]
